# Generated by Django 5.0.6 on 2024-06-11 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundryappapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laundry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hp', models.CharField(max_length=15)),
                ('nama', models.CharField(max_length=100)),
                ('jenis_laundry', models.CharField(max_length=50)),
                ('jumlah_berat', models.PositiveIntegerField()),
                ('tanggal_masuk', models.DateField()),
                ('tanggal_selesai', models.DateField()),
                ('total_harga', models.PositiveIntegerField()),
                ('catatan_khusus', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('0', 'Pending'), ('1', 'Selesai')], default='0', max_length=1)),
            ],
            options={
                'verbose_name': 'Laundry',
                'verbose_name_plural': 'Laundries',
                'db_table': 'laundry',
            },
        ),
    ]
