# Generated by Django 5.0.6 on 2024-06-11 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundryappapi', '0004_alter_laundry_options_alter_laundry_catatan_khusus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laundry',
            name='jenis_laundry',
            field=models.CharField(choices=[('cucibiasa', 'Cuci Biasa (Rp 7.000/kg)'), ('cuciexpress', 'Cuci Express (Rp 10.000/kg)'), ('setrikasaja', 'Setrika Saja (Rp 5.000/kg)'), ('cucisprei', 'Cuci Sprei (Rp 10.000/pcs)'), ('cucijas', 'Cuci Jas (Rp 20.000/pcs)')], max_length=50),
        ),
    ]
