# Generated by Django 5.0.6 on 2024-06-11 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundryappapi', '0005_alter_laundry_jenis_laundry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laundry',
            name='jenis_laundry',
            field=models.CharField(max_length=50),
        ),
    ]
