# Generated by Django 5.0.6 on 2024-07-11 02:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LaundryStore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('laundry_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laundryappapi.laundrystore')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hp', models.CharField(max_length=15)),
                ('nama', models.CharField(max_length=100)),
                ('tanggal_masuk', models.DateField()),
                ('tanggal_selesai', models.DateField()),
                ('total_harga', models.DecimalField(decimal_places=2, max_digits=10)),
                ('catatan_khusus', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('0', 'Proses'), ('1', 'Selesai')], default='0', max_length=1)),
                ('status_pembayaran', models.CharField(choices=[('0', 'Belum'), ('1', 'Lunas')], default='0', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laundryappapi.customer')),
                ('laundry_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laundryappapi.laundrystore')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('jenis_laundry', models.CharField(max_length=50)),
                ('jumlah_berat', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='laundryappapi.order')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateTimeField()),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card'), ('Transfer', 'Transfer')], max_length=10)),
                ('laundry_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laundryappapi.laundrystore')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laundryappapi.order')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('laundry_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laundryappapi.laundrystore')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Kasir', 'Kasir')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('laundry_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laundryappapi.laundrystore')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
