# Generated by Django 5.0.6 on 2024-06-11 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laundryappapi', '0002_laundry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
