# Generated by Django 5.0.6 on 2024-06-11 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundryappapi', '0003_delete_book'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='laundry',
            options={},
        ),
        migrations.AlterField(
            model_name='laundry',
            name='catatan_khusus',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='laundry',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='laundry',
            name='jumlah_berat',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='laundry',
            name='status',
            field=models.CharField(choices=[('0', 'Proses'), ('1', 'Selesai')], max_length=1),
        ),
        migrations.AlterField(
            model_name='laundry',
            name='total_harga',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterModelTable(
            name='laundry',
            table=None,
        ),
    ]
