# Generated by Django 5.0.6 on 2024-06-16 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundryappapi', '0006_alter_laundry_jenis_laundry'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaundryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_laundry', models.CharField(max_length=50)),
                ('jumlah_berat', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hp', models.CharField(max_length=15)),
                ('nama', models.CharField(max_length=100)),
                ('tanggal_masuk', models.DateField()),
                ('tanggal_selesai', models.DateField()),
                ('total_harga', models.DecimalField(decimal_places=2, max_digits=10)),
                ('catatan_khusus', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('0', 'Proses'), ('1', 'Selesai')], max_length=1)),
            ],
        ),
        migrations.DeleteModel(
            name='Laundry',
        ),
        migrations.AddField(
            model_name='laundryitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='laundryappapi.order'),
        ),
    ]
